# https://arslan.io/2021/02/15/automatic-dark-mode-for-terminal-applications/
import:
  - ~/.dotfiles/colors.yml

font:
  size: 15.0
  normal:
    family: DankMono Nerd Font

key_bindings:
  - { key: F, mods: Alt, chars: "\x1bf" }
  - { key: B, mods: Alt, chars: "\x1bb" }
  # https://github.com/jwilm/alacritty/issues/93#issuecomment-427592040
  - { key: D, mods: Alt, chars: "\x1bd" }

live_config_reload: true
