# yaml-language-server: $schema=https://raw.githubusercontent.com/distinction-dev/alacritty-schema/main/alacritty/reference.json
# https://arslan.io/2021/02/15/automatic-dark-mode-for-terminal-applications/
import:
  - ~/.dotfiles/colors.yml

font:
  size: 15.0
  normal:
    family: DankMono Nerd Font

window:
  opacity: 1.0
  dynamic_padding: true
  dimensions:
    columns: 175
    lines: 55 

key_bindings:
  - { key: F, mods: Alt, chars: "\x1bf" }
  - { key: B, mods: Alt, chars: "\x1bb" }
  # https://github.com/jwilm/alacritty/issues/93#issuecomment-427592040
  - { key: D, mods: Alt, chars: "\x1bd" }
  - { key: Q, mods: Alt, chars: "\x1bq" }

live_config_reload: true
