require("plugins")
require("config.cmp")
require("config.lsp")
require("config.telescope")
require("config.treesitter")
require("config.formatter")
require("config.lualine")
require("config.theme")
require("config.rust-config")
require("config.nerd-tree")

